#!/bin/bash

# "wg show all dump" appends the port to the public IP (e.g. 1.2.3.4:55555) 
# we just want the IP so we split on ':'
# private IP has the CIDR appened to it (e.g. 10.5.6.7/24) so we split on '/'

which jq || { echo "jq required"; exit 1; }

wg show all dump | \
  jq -R '
  split("\t") | {
    interface:  .[0],
    publickey:  .[1],
    public_ip:  .[3] | split(":")[0],
    private_ip: .[4] | split("/")[0],
    latest_handshake: .[5],
    tx: .[6],
    rx: .[7],
    timestamp: now | todateiso8601
  }
' > wireguard-status.json
