#!/bin/bash

# "wg show all dump" appends the port to the public IP (e.g. 1.2.3.4:55555) 
# we just want the IP so we split on ':'
# private IP has the CIDR appended to it (e.g. 10.5.6.7/24) so we split on '/'

which jq || { echo "jq required"; exit 1; }

wg show all dump | \
  jq -R '
  split("\t") | select(length > 5) | {
    interface:  .[0],
    publickey:  .[1],
    public_ip:  .[3] | split(":")[0],
    private_ip: .[4] | split("/")[0],
    latest_handshake: (.[5] | tonumber),
    tx: (.[6] | tonumber),
    rx: (.[7] | tonumber),
    timestamp: now | todateiso8601
  }' > /home/ubuntu/wireguard.0


grep AllowedIPs /etc/wireguard/*.peer | grep -E '[A-Z]{2}-[A-Z]{2}' | jq -R '
  split("/") | { 
    hostname:   .[3] | split(".")[0], 
    private_ip: .[3] | split(" ")[2]  
   }' > wireguard.1

jq -sc '[group_by(.private_ip)[]|add]' wireguard.0 wireguard.1 > wireguard.json
